### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by gtmx23** [coruubc/diverse_price_prediction#2]
Goals for Milestone 1:

- [ ] Understand data schema, 
- [ ] Clarify objectives,
- [ ] Finish the presentation, 
- [ ] Build the skeleton of proposal report, 
- [ ] Finalize team contract, 
- [ ] Set up weekly goals.

**Comment by gtmx23** [comment]
Changing this to an actual Milestone (initial issue was posted to check on collaboration permissions)
